apiVersion: v1
kind: Service
metadata:
  name: j-master
  labels:
    app: j-master
spec:
  type: NodePort
  ports:
  - port: 1099
    targetPort: 30000
    name: http
  selector:
    app: j-master
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: j-master
  labels:
    app: j-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: j-master
  serviceName: j-master    
  template:
    metadata:
      labels:
        app: j-master
    spec:
      terminationGracePeriodSeconds: 300
      containers:
      - name: j-master
        image: saikrishnaoduru/jmeter:latest
        imagePullPolicy: Always
        args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 1099
          name: j-master
        resources:
          limits:
            memory: 1024Mi
            cpu: 1000m
          requests:
            cpu: 1000m
            memory: 1024Mi
      restartPolicy: Always     
